branch-defaults:
  master:
    environment: eb-development
global:
  application_name: MyWebApplication
  default_ec2_keyname: aws_demo
  default_platform: Docker 1.7.1
  default_region: us-west-2
  profile: null
  sc: git
